<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <RootNamespace>LAB1</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
      <_ContentIncludedByDefault Remove="Views\Shared\Shared\CalculatorError.cshtml" />
      <_ContentIncludedByDefault Remove="Views\Shared\Shared\Error.cshtml" />
      <_ContentIncludedByDefault Remove="Views\Shared\Shared\_Layout.cshtml" />
      <_ContentIncludedByDefault Remove="Views\Shared\Shared\_ValidationScriptsPartial.cshtml" />
      <_ContentIncludedByDefault Remove="Views\Shared\Error.cshtml" />
      <_ContentIncludedByDefault Remove="Views\Shared\_Layout.cshtml" />
      <_ContentIncludedByDefault Remove="Views\Shared\_ValidationScriptsPartial.cshtml" />
      <_ContentIncludedByDefault Remove="Shared\CalculatorError.cshtml" />
      <_ContentIncludedByDefault Remove="Shared\Error.cshtml" />
      <_ContentIncludedByDefault Remove="Shared\_Layout.cshtml" />
      <_ContentIncludedByDefault Remove="Shared\_ValidationScriptsPartial.cshtml" />
      <_ContentIncludedByDefault Remove="Views\Home\About.cshtml" />
      <_ContentIncludedByDefault Remove="Views\Home\Calculator.cshtml" />
      <_ContentIncludedByDefault Remove="Views\Home\Index.cshtml" />
      <_ContentIncludedByDefault Remove="Views\Home\Privacy.cshtml" />
      <_ContentIncludedByDefault Remove="Views\Shared\CalculatorError.cshtml" />
      <_ContentIncludedByDefault Remove="Views\_ViewImports.cshtml" />
      <_ContentIncludedByDefault Remove="Views\_ViewStart.cshtml" />
      <_ContentIncludedByDefault Remove="Home\Index.cshtml" />
      <_ContentIncludedByDefault Remove="Home\Privacy.cshtml" />
      <_ContentIncludedByDefault Remove="Views\Birth\Error.cshtml" />
      <_ContentIncludedByDefault Remove="Views\Birth\Form.cshtml" />
      <_ContentIncludedByDefault Remove="Views\Birth\Result.cshtml" />
      <_ContentIncludedByDefault Remove="Views\Calculator\Form.cshtml" />
      <_ContentIncludedByDefault Remove="Views\Calculator\Result.cshtml" />
      <_ContentIncludedByDefault Remove="Views\Contact\Add.cshtml" />
      <_ContentIncludedByDefault Remove="Views\Contact\Index.cshtml" />
      <_ContentIncludedByDefault Remove="Views\Home\CalculatorError.cshtml" />
    </ItemGroup>

    <ItemGroup>
      <UpToDateCheckInput Remove="Shared\Error.cshtml" />
      <UpToDateCheckInput Remove="Shared\_Layout.cshtml" />
      <UpToDateCheckInput Remove="Shared\_ValidationScriptsPartial.cshtml" />
    </ItemGroup>

</Project>
